name: Build Project

on: 
  workflow_run: # Start after tests
    workflows: ["Test project"]
    types:
      - completed
  
  
jobs:
  buildForAllDesiredPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:		
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux # Build for a Linux standalone
          - StandaloneLinux64 # Build for a Linux 64-bit standalone
          - WebGL # Build for WebGL.

         # comment or uncomment your desired platforms
         
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Deploy WebGL build
        if: ${{ matrix.targetPlatform == 'WebGL' }} # Run only for WebGL
        run: |
          # Create gh-pages branch if it doesn't exist
          git config --global user.name "GitHub Actions"
          git checkout -b gh-pages || git checkout gh-pages
          
          # Clear out old build (if exists)
          rm -rf ./build/*
          
          # Copy the WebGL build into the directory that GitHub Pages uses
          cp -r ./build/WebGL/* .

          # Add, commit, and push to gh-pages branch
          git add .
          git commit -m "Deploy WebGL build"
          git push origin gh-pages --force
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
